### ISSUE TITLE
File cannot be uploaded error

### ISSUE THREAD

**Issue by dustinleblanc** [thom8/acquia-vagrant#2]
Great project! was super fast to setup and easy to share with a team for acquia sites. 

We are having one issue it seems that Im guessing is related to NFS file shares on encrypted disks but Im not sure. 

We are having problems when someone attempts to upload a file using one of our file fields in development (testing that a feature works before deploying to dev)

![error uploading image](https://i.imgur.com/HKEwHGC.png)

Any ideas on how to handle this?

I tried _not_ setting NFS mode on and it causes the site to not load with a 403 error from apache.

Thanks!

**Comment by thom8** [comment]
Thanks!

I have run into this issue before and it has to do with the ownership/permissions of the files directory.
As a workaround I've just added the www-data user to the dialout group which is default for NFS shares on vbox.

Would you be able to attempt to replicate the issue with the [example project](https://github.com/thom8/acquia-vagrant-example) - just create an article and attach an image.

If this fails try --

```
sudo usermod -a -G dialout www-data
```

If this works I'll push this back into the provisioning stage so it's set by default. Otherwise in the meantime you can add this as an extra provisioning step to the Vagrant file eg.

```
config.vm.provision "shell", inline: "sudo usermod -a -G dialout www-data && sudo chmod -R 775 /drupal/sites/default/files"
```

**Comment by dustinleblanc** [comment]
Giving it a shot, will report back

**Comment by dustinleblanc** [comment]
Actually it works flawlessly on the example site. I am guessing this has something to do with the fact that the site in question is an existing site we were developing locally (I was just using drush's php-server) and I have added the vagrant config to the project. this means the files directory and all that jazz already existed. 

I am going to try removing the files directory, letting vagrant run the installer before I sync down the remote database, etc.

Thanks for the quick response!

**Comment by dustinleblanc** [comment]
hmm, no luck, also tried the usermod steps. One thing that is interesting, this is what I get from the vagrant box for permissions:

```
vagrant@litehouse:/drupal/sites/default$ ls -lah
total 100K
dr-xr-x---    8 501 70  272 Oct 16 12:22 .
drwxr-x---    8 501 70  272 Oct  9 15:29 ..
-rw-r-----    1 501 70  25K Jun  9 19:19 default.settings.php
-rw-r--r--    1 501 70 8.1K Aug 19 17:07 .DS_Store
-rw-r--r--    1 501 70 1012 Oct 15 19:30 example.settings.local.php
drwxrwxr-x 1072 501 70  36K Oct 16 02:33 files
-rw-r-----    1 501 70 1.5K Oct 15 17:13 settings.local.php
-r--r--r--    1 501 70 7.8K Oct 15 19:29 settings.php
vagrant@litehouse:/drupal/sites/default$
```

From what I've read this means something is screwy with the box's permissions?

**Comment by dustinleblanc** [comment]
I fixed the issue by adding this to the Vagrantfile:

```
config.vm.synced_folder "./docroot", "/drupal", id: "drupal",
  owner: "vagrant",
  group: "www-data",
  mount_options: ["dmode=775,fmode=664"]
```
